
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 11 18:17:01 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UMINUS = 12;
  public static final int GTOREQ = 23;
  public static final int INT = 31;
  public static final int FOR = 34;
  public static final int MINUS = 9;
  public static final int CP = 3;
  public static final int NOT = 19;
  public static final int SEMICOLON = 6;
  public static final int AND = 17;
  public static final int LT = 20;
  public static final int OR = 18;
  public static final int COMMA = 7;
  public static final int OP = 2;
  public static final int INC = 15;
  public static final int DIV = 11;
  public static final int PLUS = 8;
  public static final int CB = 5;
  public static final int IF = 26;
  public static final int EOF = 0;
  public static final int ASIG = 14;
  public static final int OB = 4;
  public static final int error = 1;
  public static final int MUL = 10;
  public static final int NUMBER = 33;
  public static final int MOD = 13;
  public static final int EQ = 24;
  public static final int ELSE = 27;
  public static final int TO = 35;
  public static final int WHILE = 28;
  public static final int LTOREQ = 22;
  public static final int DOWNTO = 37;
  public static final int DEC = 16;
  public static final int GT = 21;
  public static final int VAR = 32;
  public static final int PRINT = 30;
  public static final int DO = 29;
  public static final int STEP = 36;
  public static final int NOTEQ = 25;
}

